//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./ShaderLab.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IShaderLabListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class ShaderLabBaseListener : IShaderLabListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.shader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShader([NotNull] ShaderLabParser.ShaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.shader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShader([NotNull] ShaderLabParser.ShaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.properties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperties([NotNull] ShaderLabParser.PropertiesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.properties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperties([NotNull] ShaderLabParser.PropertiesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] ShaderLabParser.PropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] ShaderLabParser.PropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_int([NotNull] ShaderLabParser.Property_intContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_int([NotNull] ShaderLabParser.Property_intContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_float"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_float([NotNull] ShaderLabParser.Property_floatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_float"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_float([NotNull] ShaderLabParser.Property_floatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_range([NotNull] ShaderLabParser.Property_rangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_range([NotNull] ShaderLabParser.Property_rangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_color([NotNull] ShaderLabParser.Property_colorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_color([NotNull] ShaderLabParser.Property_colorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_vector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_vector([NotNull] ShaderLabParser.Property_vectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_vector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_vector([NotNull] ShaderLabParser.Property_vectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_2d"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_2d([NotNull] ShaderLabParser.Property_2dContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_2d"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_2d([NotNull] ShaderLabParser.Property_2dContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_cube"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_cube([NotNull] ShaderLabParser.Property_cubeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_cube"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_cube([NotNull] ShaderLabParser.Property_cubeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_3d"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_3d([NotNull] ShaderLabParser.Property_3dContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_3d"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_3d([NotNull] ShaderLabParser.Property_3dContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.category"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCategory([NotNull] ShaderLabParser.CategoryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.category"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCategory([NotNull] ShaderLabParser.CategoryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.kernel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKernel([NotNull] ShaderLabParser.KernelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.kernel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKernel([NotNull] ShaderLabParser.KernelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.hlsl_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHlsl_block([NotNull] ShaderLabParser.Hlsl_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.hlsl_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHlsl_block([NotNull] ShaderLabParser.Hlsl_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.tags"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTags([NotNull] ShaderLabParser.TagsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.tags"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTags([NotNull] ShaderLabParser.TagsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTag([NotNull] ShaderLabParser.TagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTag([NotNull] ShaderLabParser.TagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.common_state"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommon_state([NotNull] ShaderLabParser.Common_stateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.common_state"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommon_state([NotNull] ShaderLabParser.Common_stateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.cull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCull([NotNull] ShaderLabParser.CullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.cull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCull([NotNull] ShaderLabParser.CullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.ztest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterZtest([NotNull] ShaderLabParser.ZtestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.ztest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitZtest([NotNull] ShaderLabParser.ZtestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.zwrite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterZwrite([NotNull] ShaderLabParser.ZwriteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.zwrite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitZwrite([NotNull] ShaderLabParser.ZwriteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.color_mask"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColor_mask([NotNull] ShaderLabParser.Color_maskContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.color_mask"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColor_mask([NotNull] ShaderLabParser.Color_maskContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.meta"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeta([NotNull] ShaderLabParser.MetaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.meta"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeta([NotNull] ShaderLabParser.MetaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] ShaderLabParser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] ShaderLabParser.RangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.tag_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTag_key([NotNull] ShaderLabParser.Tag_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.tag_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTag_key([NotNull] ShaderLabParser.Tag_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.tag_val"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTag_val([NotNull] ShaderLabParser.Tag_valContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.tag_val"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTag_val([NotNull] ShaderLabParser.Tag_valContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.shader_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShader_name([NotNull] ShaderLabParser.Shader_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.shader_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShader_name([NotNull] ShaderLabParser.Shader_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.display_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplay_name([NotNull] ShaderLabParser.Display_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.display_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplay_name([NotNull] ShaderLabParser.Display_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.texture_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTexture_name([NotNull] ShaderLabParser.Texture_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.texture_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTexture_name([NotNull] ShaderLabParser.Texture_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_identifier([NotNull] ShaderLabParser.Property_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_identifier([NotNull] ShaderLabParser.Property_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.val_int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVal_int([NotNull] ShaderLabParser.Val_intContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.val_int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVal_int([NotNull] ShaderLabParser.Val_intContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.val_float"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVal_float([NotNull] ShaderLabParser.Val_floatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.val_float"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVal_float([NotNull] ShaderLabParser.Val_floatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.val_min"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVal_min([NotNull] ShaderLabParser.Val_minContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.val_min"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVal_min([NotNull] ShaderLabParser.Val_minContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.val_max"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVal_max([NotNull] ShaderLabParser.Val_maxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.val_max"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVal_max([NotNull] ShaderLabParser.Val_maxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.val_vec4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVal_vec4([NotNull] ShaderLabParser.Val_vec4Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.val_vec4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVal_vec4([NotNull] ShaderLabParser.Val_vec4Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.channel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChannel([NotNull] ShaderLabParser.ChannelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.channel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChannel([NotNull] ShaderLabParser.ChannelContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
