//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./ShaderLab.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ShaderLabParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IShaderLabListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.shader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShader([NotNull] ShaderLabParser.ShaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.shader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShader([NotNull] ShaderLabParser.ShaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperties([NotNull] ShaderLabParser.PropertiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperties([NotNull] ShaderLabParser.PropertiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty([NotNull] ShaderLabParser.PropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty([NotNull] ShaderLabParser.PropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_int([NotNull] ShaderLabParser.Property_intContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_int([NotNull] ShaderLabParser.Property_intContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_float"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_float([NotNull] ShaderLabParser.Property_floatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_float"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_float([NotNull] ShaderLabParser.Property_floatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_range([NotNull] ShaderLabParser.Property_rangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_range([NotNull] ShaderLabParser.Property_rangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_color([NotNull] ShaderLabParser.Property_colorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_color([NotNull] ShaderLabParser.Property_colorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_vector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_vector([NotNull] ShaderLabParser.Property_vectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_vector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_vector([NotNull] ShaderLabParser.Property_vectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_2d([NotNull] ShaderLabParser.Property_2dContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_2d([NotNull] ShaderLabParser.Property_2dContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_cube"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_cube([NotNull] ShaderLabParser.Property_cubeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_cube"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_cube([NotNull] ShaderLabParser.Property_cubeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_3d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_3d([NotNull] ShaderLabParser.Property_3dContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_3d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_3d([NotNull] ShaderLabParser.Property_3dContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.category"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCategory([NotNull] ShaderLabParser.CategoryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.category"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCategory([NotNull] ShaderLabParser.CategoryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.kernel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKernel([NotNull] ShaderLabParser.KernelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.kernel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKernel([NotNull] ShaderLabParser.KernelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.hlsl_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHlsl_block([NotNull] ShaderLabParser.Hlsl_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.hlsl_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHlsl_block([NotNull] ShaderLabParser.Hlsl_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.tags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTags([NotNull] ShaderLabParser.TagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.tags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTags([NotNull] ShaderLabParser.TagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTag([NotNull] ShaderLabParser.TagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTag([NotNull] ShaderLabParser.TagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.common_state"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommon_state([NotNull] ShaderLabParser.Common_stateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.common_state"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommon_state([NotNull] ShaderLabParser.Common_stateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.cull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCull([NotNull] ShaderLabParser.CullContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.cull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCull([NotNull] ShaderLabParser.CullContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.ztest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterZtest([NotNull] ShaderLabParser.ZtestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.ztest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitZtest([NotNull] ShaderLabParser.ZtestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.zwrite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterZwrite([NotNull] ShaderLabParser.ZwriteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.zwrite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitZwrite([NotNull] ShaderLabParser.ZwriteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.color_mask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColor_mask([NotNull] ShaderLabParser.Color_maskContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.color_mask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColor_mask([NotNull] ShaderLabParser.Color_maskContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.meta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeta([NotNull] ShaderLabParser.MetaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.meta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeta([NotNull] ShaderLabParser.MetaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange([NotNull] ShaderLabParser.RangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange([NotNull] ShaderLabParser.RangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.tag_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTag_key([NotNull] ShaderLabParser.Tag_keyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.tag_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTag_key([NotNull] ShaderLabParser.Tag_keyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.tag_val"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTag_val([NotNull] ShaderLabParser.Tag_valContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.tag_val"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTag_val([NotNull] ShaderLabParser.Tag_valContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.shader_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShader_name([NotNull] ShaderLabParser.Shader_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.shader_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShader_name([NotNull] ShaderLabParser.Shader_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.display_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplay_name([NotNull] ShaderLabParser.Display_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.display_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplay_name([NotNull] ShaderLabParser.Display_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.texture_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTexture_name([NotNull] ShaderLabParser.Texture_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.texture_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTexture_name([NotNull] ShaderLabParser.Texture_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.property_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_identifier([NotNull] ShaderLabParser.Property_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.property_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_identifier([NotNull] ShaderLabParser.Property_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.val_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVal_int([NotNull] ShaderLabParser.Val_intContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.val_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVal_int([NotNull] ShaderLabParser.Val_intContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.val_float"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVal_float([NotNull] ShaderLabParser.Val_floatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.val_float"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVal_float([NotNull] ShaderLabParser.Val_floatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.val_min"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVal_min([NotNull] ShaderLabParser.Val_minContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.val_min"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVal_min([NotNull] ShaderLabParser.Val_minContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.val_max"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVal_max([NotNull] ShaderLabParser.Val_maxContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.val_max"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVal_max([NotNull] ShaderLabParser.Val_maxContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.val_vec4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVal_vec4([NotNull] ShaderLabParser.Val_vec4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.val_vec4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVal_vec4([NotNull] ShaderLabParser.Val_vec4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderLabParser.channel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChannel([NotNull] ShaderLabParser.ChannelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderLabParser.channel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChannel([NotNull] ShaderLabParser.ChannelContext context);
}
